In [1]:
# import NumPy for numerical operations
import numpy as np

# import Pandas for data manipulation
import pandas as pd

# import train_test_split to split the dataset
from sklearn.model_selection import train_test_split

# import MissingIndicator to create missing value indicator columns
# import SimpleImputer to fill missing values
from sklearn.impute import MissingIndicator, SimpleImputer

In [2]:
# load only the required columns from the CSV file
df = pd.read_csv(
    'train.csv',
    usecols=['Age', 'Fare', 'Survived']
)

In [3]:
# show the first 5 rows of the dataset
df.head()

,Survived,Age,Fare
0,0,22.0,7.2500
1,1,38.0,71.2833
2,1,26.0,7.9250
3,1,35.0,53.1000
4,0,35.0,8.0500


In [4]:
# create the input features by removing the target column
X = df.drop(columns=['Survived'])

# store the target column separately
y = df['Survived']

In [5]:
# split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,      # use 20% of the data for testing
    random_state=2      # ensure the same split every time
)

In [6]:
# show the first 5 rows of the training dataset
X_train.head()

,Age,Fare
30,40.0,27.7208
10,4.0,16.7000
873,47.0,9.0000
182,9.0,31.3875
876,20.0,9.8458


In [7]:
# create a SimpleImputer object with the default strategy
si = SimpleImputer()

# learn the imputation values from the training data and transform it
X_train_trf = si.fit_transform(X_train)

# apply the same imputation to the testing data
X_test_trf = si.transform(X_test)

In [8]:
# display the transformed training data
X_train_trf

array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]])

In [9]:
# import the Logistic Regression model
from sklearn.linear_model import LogisticRegression

# create a Logistic Regression model
clf = LogisticRegression()

# train the model using the transformed training data
clf.fit(X_train_trf, y_train)

# predict the target values for the testing data
y_pred = clf.predict(X_test_trf)

# import the accuracy evaluation metric
from sklearn.metrics import accuracy_score

# calculate the model accuracy
accuracy_score(y_test, y_pred)

0.6145251396648045

## **Using Missing Imputer**

In [10]:
# create a MissingIndicator object
mi = MissingIndicator()

# learn which columns contain missing values in the training data
mi.fit(X_train)

MissingIndicator()

In [11]:
# display the indices of the columns that contain missing values
mi.features_

array([0])

In [12]:
# create missing value indicator columns for the training data
X_train_missing = mi.transform(X_train)

In [13]:
# display the missing value indicator array
X_train_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [14]:
# create missing value indicator columns for the testing data
X_test_missing = mi.transform(X_test)

In [15]:
# display the missing value indicator array for the testing data
X_test_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [16]:
# add the missing value indicator as a new column
X_train['Age_NA'] = X_train_missing

In [17]:
# display the training dataset
X_train

,Age,Fare,Age_NA
30,40.0,27.7208,False
10,4.0,16.7000,False
873,47.0,9.0000,False
182,9.0,31.3875,False
876,20.0,9.8458,False
...,...,...,...
534,30.0,8.6625,False
584,NaN,8.7125,True
493,71.0,49.5042,False
527,NaN,221.7792,True


In [18]:
# add the missing value indicator as a new column in the testing data
X_test['Age_NA'] = X_test_missing

In [19]:
# display the test dataset
X_test

,Age,Fare,Age_NA
707,42.0,26.2875,False
37,21.0,8.0500,False
615,24.0,65.0000,False
169,28.0,56.4958,False
68,17.0,7.9250,False
...,...,...,...
89,24.0,8.0500,False
80,22.0,9.0000,False
846,NaN,69.5500,True
870,26.0,7.8958,False


In [20]:
# create simple imputer object with default strategy to replace missing values with mean
si = SimpleImputer()

# fit imputer on training data and transform training data by filling missing values
X_train_trf2 = si.fit_transform(X_train)

# transform testing data using values learned from training data
X_test_trf2 = si.transform(X_test)

In [21]:
# import logistic regression algorithm for classification
from sklearn.linear_model import LogisticRegression

# create logistic regression model object
clf = LogisticRegression()

# train the model using transformed training data
clf.fit(X_train_trf2,y_train)

# predict target values for transformed test data
y_pred = clf.predict(X_test_trf2)

# import accuracy score metric to evaluate model performance
from sklearn.metrics import accuracy_score

# calculate accuracy of the model predictions
accuracy_score(y_test,y_pred)

0.6312849162011173

Accuracy Improved a bit

## **Using Simple Imputer**

In [22]:
# create simple imputer object to fill missing values and add missing value indicator columns
si = SimpleImputer(add_indicator=True)

In [23]:
# fill missing values in training data and add missing value indicator columns
X_train = si.fit_transform(X_train)

In [24]:
# transform test data by filling missing values and adding missing value indicator columns
X_test = si.transform(X_test)

In [25]:
# import logistic regression algorithm for classification
from sklearn.linear_model import LogisticRegression

# create logistic regression model object
clf = LogisticRegression()

# train the model using transformed training data
clf.fit(X_train_trf2,y_train)

# predict target values for transformed test data
y_pred = clf.predict(X_test_trf2)

# import accuracy score metric to evaluate model performance
from sklearn.metrics import accuracy_score

# calculate accuracy of the model predictions
accuracy_score(y_test,y_pred)

0.6312849162011173