In [1]:
# import pandas library for data manipulation
import pandas as pd

# import numpy library for numerical operations
import numpy as np

# import linear regression model for predicting continuous values
from sklearn.linear_model import LinearRegression

In [2]:
# read dataset, select required columns, scale values, and round them
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)

# set random seed for reproducible sampling
np.random.seed(9)

# randomly select 5 rows from the dataset
df = df.sample(5)

# display the sampled dataframe
df

,R&D Spend,Administration,Marketing Spend,Profit
21,8.0,15.0,30.0,11.0
37,4.0,5.0,20.0,9.0
2,15.0,10.0,41.0,19.0
14,12.0,16.0,26.0,13.0
44,2.0,15.0,3.0,7.0


In [3]:
# remove the target column and keep only input feature columns
df = df.iloc[:,0:-1]

# display the updated dataframe
df

,R&D Spend,Administration,Marketing Spend
21,8.0,15.0,30.0
37,4.0,5.0,20.0
2,15.0,10.0,41.0
14,12.0,16.0,26.0
44,2.0,15.0,3.0


In [4]:
# insert a missing value in the first feature of the second row
df.iloc[1,0] = np.nan

# insert a missing value in the second feature of the fourth row
df.iloc[3,1] = np.nan

# insert a missing value in the last feature of the last row
df.iloc[-1,-1] = np.nan

/tmp/ipykernel_9049/1381089433.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
/tmp/ipykernel_9049/1381089433.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
/tmp/ipykernel_9049/1381089433.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.nan


In [5]:
# display first five rows of the dataframe
df.head()

,R&D Spend,Administration,Marketing Spend
21,8.0,15.0,30.0
37,NaN,5.0,20.0
2,15.0,10.0,41.0
14,12.0,NaN,26.0
44,2.0,15.0,NaN


In [6]:
# create a new dataframe to store imputed values
df0 = pd.DataFrame()

# fill missing values in R&D Spend with its column mean
df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())

# fill missing values in Administration with its column mean
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())

# fill missing values in Marketing Spend with its column mean
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [7]:
# display dataframe after completing the first imputation iteration
df0

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.00
37,9.25,5.00,20.00
2,15.00,10.00,41.00
14,12.00,11.25,26.00
44,2.00,15.00,29.25


In [8]:
# create a copy of the imputed dataframe for the next iteration
df1 = df0.copy()

# restore the original missing value in the first column of the second row
df1.iloc[1,0] = np.nan

# display the updated dataframe
df1

,R&D Spend,Administration,Marketing Spend
21,8.0,15.00,30.00
37,NaN,5.00,20.00
2,15.0,10.00,41.00
14,12.0,11.25,26.00
44,2.0,15.00,29.25


In [9]:
# select rows without missing target value and use remaining columns as features
X = df1.iloc[[0,2,3,4],1:3]

# display the feature dataset
X

,Administration,Marketing Spend
21,15.00,30.00
2,10.00,41.00
14,11.25,26.00
44,15.00,29.25


In [10]:
# select corresponding values of the first column as target variable
y = df1.iloc[[0,2,3,4],0]

# display the target variable
y

,R&D Spend
21,8.0
2,15.0
14,12.0
44,2.0


In [11]:
# create linear regression model object
lr = LinearRegression()

# train the model using selected features and target values
lr.fit(X,y)

# predict the missing value using the trained model
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([23.14158651])

In [12]:
# replace the missing value with the predicted value
df1.iloc[1,0] = 23.14

In [13]:
# display the dataframe after replacing the missing value with the predicted value
df1

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.00
37,23.14,5.00,20.00
2,15.00,10.00,41.00
14,12.00,11.25,26.00
44,2.00,15.00,29.25


In [14]:
# restore the original missing value in the second column of the fourth row
df1.iloc[3,1] = np.nan

# display the updated dataframe
df1

,R&D Spend,Administration,Marketing Spend
21,8.00,15.0,30.00
37,23.14,5.0,20.00
2,15.00,10.0,41.00
14,12.00,NaN,26.00
44,2.00,15.0,29.25


In [15]:
# select rows without missing target value and choose required feature columns
X = df1.iloc[[0,1,2,4],[0,2]]

# display the feature dataset
X

,R&D Spend,Marketing Spend
21,8.00,30.00
37,23.14,20.00
2,15.00,41.00
44,2.00,29.25


In [16]:
# select corresponding values of the second column as target variable
y = df1.iloc[[0,1,2,4],1]

# display the target variable
y

,Administration
21,15.0
37,5.0
2,10.0
44,15.0


In [17]:
# create linear regression model object
lr = LinearRegression()

# train the model using selected features and target values
lr.fit(X,y)

# predict the missing value using the trained model
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.06331285])

In [18]:
# replace the missing value with the predicted value
df1.iloc[3,1] = 11.06

In [19]:
# display the dataframe after replacing the missing value with the predicted value
df1

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.00
37,23.14,5.00,20.00
2,15.00,10.00,41.00
14,12.00,11.06,26.00
44,2.00,15.00,29.25


In [20]:
# restore the original missing value in the last column of the last row
df1.iloc[4,-1] = np.nan

# display the updated dataframe
df1

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.0
37,23.14,5.00,20.0
2,15.00,10.00,41.0
14,12.00,11.06,26.0
44,2.00,15.00,NaN


In [21]:
# select rows without missing target value and use first two columns as features
X = df1.iloc[0:4,0:2]

# display the feature dataset
X

,R&D Spend,Administration
21,8.00,15.00
37,23.14,5.00
2,15.00,10.00
14,12.00,11.06


In [22]:
# select corresponding values of the last column as target variable
y = df1.iloc[0:4,-1]

# display the target variable
y

,Marketing Spend
21,30.0
37,20.0
2,41.0
14,26.0


In [23]:
# create linear regression model object
lr = LinearRegression()

# train the model using selected features and target values
lr.fit(X,y)

# predict the missing value using the trained model
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([31.56351448])

In [24]:
# replace the missing value with the predicted value
df1.iloc[4,-1] = 31.56

In [25]:
# display dataframe after completing the first iteration of imputation
df1

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.00
37,23.14,5.00,20.00
2,15.00,10.00,41.00
14,12.00,11.06,26.00
44,2.00,15.00,31.56


In [26]:
# compare first iteration values with initial imputed values
df1 - df0

,R&D Spend,Administration,Marketing Spend
21,0.00,0.00,0.00
37,13.89,0.00,0.00
2,0.00,0.00,0.00
14,0.00,-0.19,0.00
44,0.00,0.00,2.31


In [27]:
# create a copy of the first iteration dataframe for the next iteration
df2 = df1.copy()

# restore the original missing value in the first column of the second row
df2.iloc[1,0] = np.nan

# display the updated dataframe
df2

,R&D Spend,Administration,Marketing Spend
21,8.0,15.00,30.00
37,NaN,5.00,20.00
2,15.0,10.00,41.00
14,12.0,11.06,26.00
44,2.0,15.00,31.56


In [28]:
# select rows without missing target value and use remaining columns as features
X = df2.iloc[[0,2,3,4],1:3]

# select corresponding values of the first column as target variable
y = df2.iloc[[0,2,3,4],0]

# create linear regression model object
lr = LinearRegression()

# train the model using selected features and target values
lr.fit(X,y)

# predict the missing value using the trained model
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([23.78627207])

In [29]:
# replace the missing value with the newly predicted value
df2.iloc[1,0] = 23.78

In [30]:
# restore the original missing value in the second column
df2.iloc[3,1] = np.nan

# select rows without missing target value and choose required feature columns
X = df2.iloc[[0,1,2,4],[0,2]]

# select corresponding values of the second column as target variable
y = df2.iloc[[0,1,2,4],1]

# create linear regression model object
lr = LinearRegression()

# train the model using selected features and target values
lr.fit(X,y)

# predict the missing value using the trained model
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.22020174])

In [31]:
# replace the missing value with the newly predicted value
df2.iloc[3,1] = 11.22

In [32]:
# restore the original missing value in the last column
df2.iloc[4,-1] = np.nan

# select rows without missing target value and use first two columns as features
X = df2.iloc[0:4,0:2]

# select corresponding values of the last column as target variable
y = df2.iloc[0:4,-1]

# create linear regression model object
lr = LinearRegression()

# train the model using selected features and target values
lr.fit(X,y)

# predict the missing value using the trained model
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([38.87979054])

In [33]:
# replace the missing value with the newly predicted value
df2.iloc[4,-1] = 31.56

In [34]:
# display dataframe after completing the second iteration of imputation
df2

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.00
37,23.78,5.00,20.00
2,15.00,10.00,41.00
14,12.00,11.22,26.00
44,2.00,15.00,31.56


In [35]:
# compare second iteration values with first iteration values
df2 - df1

,R&D Spend,Administration,Marketing Spend
21,0.00,0.00,0.0
37,0.64,0.00,0.0
2,0.00,0.00,0.0
14,0.00,0.16,0.0
44,0.00,0.00,0.0


In [36]:
# create a copy of the second iteration dataframe for the next iteration
df3 = df2.copy()

# restore the original missing value in the first column of the second row
df3.iloc[1,0] = np.nan

# display the updated dataframe
df3

,R&D Spend,Administration,Marketing Spend
21,8.0,15.00,30.00
37,NaN,5.00,20.00
2,15.0,10.00,41.00
14,12.0,11.22,26.00
44,2.0,15.00,31.56


In [37]:
# select rows without missing target value and use remaining columns as features
X = df3.iloc[[0,2,3,4],1:3]

# select corresponding values of the first column as target variable
y = df3.iloc[[0,2,3,4],0]

# create linear regression model object
lr = LinearRegression()

# train the model using selected features and target values
lr.fit(X,y)

# predict the missing value using the trained model
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([24.57698058])

In [38]:
# replace the missing value with the newly predicted value
df3.iloc[1,0] = 24.57

In [39]:
# restore the original missing value in the second column
df3.iloc[3,1] = np.nan

# select rows without missing target value and choose required feature columns
X = df3.iloc[[0,1,2,4],[0,2]]

# select corresponding values of the second column as target variable
y = df3.iloc[[0,1,2,4],1]

# create linear regression model object
lr = LinearRegression()

# train the model using selected features and target values
lr.fit(X,y)

# predict the missing value using the trained model
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.37282844])

In [40]:
# replace the missing value with the newly predicted value
df3.iloc[3,1] = 11.37

In [41]:
# restore the original missing value in the last column
df3.iloc[4,-1] = np.nan

# select rows without missing target value and use first two columns as features
X = df3.iloc[0:4,0:2]

# select corresponding values of the last column as target variable
y = df3.iloc[0:4,-1]

# create linear regression model object
lr = LinearRegression()

# train the model using selected features and target values
lr.fit(X,y)

# predict the missing value using the trained model
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([45.53976417])

In [42]:
# replace the missing value with the newly predicted value
df3.iloc[4,-1] = 45.53

In [43]:
# replace the missing value with the predicted value in the second iteration dataframe
df2.iloc[3,1] = 11.22

In [44]:
# display dataframe after completing the third iteration of imputation
df3

,R&D Spend,Administration,Marketing Spend
21,8.00,15.00,30.00
37,24.57,5.00,20.00
2,15.00,10.00,41.00
14,12.00,11.37,26.00
44,2.00,15.00,45.53


In [45]:
# compare third iteration values with second iteration values
df3 - df2

,R&D Spend,Administration,Marketing Spend
21,0.00,0.00,0.00
37,0.79,0.00,0.00
2,0.00,0.00,0.00
14,0.00,0.15,0.00
44,0.00,0.00,13.97
